version: 1.2
workflows:
        - name: Scan-N-Trim
          subclass: WDL
          primaryDescriptorPath: /workflows/wf_peTrimming.wdl
          testParameterFiles:
                - empty.json



